### PR TITLE
Greet new contributors

### PR DESCRIPTION
**Pull request by CutestNekoAqua**
Added a workflow to greet new contributors and first time issuers.

Thoughts?

### CODE REVIEW

**Comment by Insert5StarName** [comment]
> Thoughts?
yes

**Comment by Mar0xy** [comment]
"Congrats on merging your" does not seem right considering contributors can't merge their own PRs

**Comment by CutestNekoAqua** [comment]
"Congrats on getting your first PR merged"?

**Comment by Mar0xy** [comment]
Yeah that would be better

**Comment by Mar0xy** [comment]
Also the action is broken see: https://github.com/wow-actions/welcome/issues/9

**Comment by CutestNekoAqua** [comment]
oh no :(

**Comment by CutestNekoAqua** [comment]
Lets see if this thingy works

**Pull request merged**
