### PR TITLE
Quick-and-dirty corner roundness toggle

### PR DESCRIPTION
**Pull request by ShittyKopper**
To keep things manageable I merged a lot of one off values into just a handful of common sizes, so some parts of the UI will look different than upstream even with the "Misskey" rounding mode.

A lot of find and replace were involved, so I definitely need another set of eyes to look over this and say what parts should be (un)rounded, marking as draft for now.

### CODE REVIEW

**Comment by ShittyKopper** [comment]
i haven't found any obvious breakages (beyond the avatar thing fixed in d4d2f6f) after running this for the last day or so, and the issues i had with locales not updating fixed itself after i rebased the pr on latest develop, un-drafting this pr

**Comment by Mar0xy** [comment]
> (beyond the avatar thing fixed in https://github.com/transfem-org/Sharkey/commit/d4d2f6f8710d8cfd43890cda09b0217a555d6ace)

Does this mean it also works fine with non-square avatars

**Comment by ShittyKopper** [comment]
yep. that radius controls the avatar roundness, which gets set to 5px with the .square class around line 189 (which gets applied by the square avatars setting)

**Comment by Mar0xy** [comment]
I see that some `5px` radiuses get set to `4px` with the radius xs variable is this intended

**Comment by Insert5StarName** [comment]
as far as i understand this is intended

**Comment by ShittyKopper** [comment]
> I see that some `5px` radiuses get set to `4px` with the radius xs variable is this intended

yep.

> To keep things manageable I merged a lot of one off values into just a handful of common sizes, so some parts of the UI will look different than upstream even with the "Misskey" rounding mode.

**Comment by Mar0xy** [comment]
Then there is also the question about `boot.js` and `error.css` where the buttons get an very high radius set wouldn't this cause issues for when the error pages show up with the buttons

**Review by Insert5StarName — APPROVED** [review]
Looks good to me honestly

**Review by Mar0xy — APPROVED** [review]

**Comment by ShittyKopper** [comment]
> Then there is also the question about `boot.js` and `error.css` where the buttons get an very high radius set wouldn't this cause issues for when the error pages show up with the buttons

those are likely the upstream values carried over from the commit reverts. i'll prolly hardcode sharkey's radius values there in a bit.

i think the stying on those pages are separate enough from the "main" misskey app that it shouldn't cause any issues either way and is just down to preference

**Comment by ShittyKopper** [comment]
nvm i took too long to write that reply

**Comment by Mar0xy** [comment]
> nvm i took too long to write that reply

rip

**Pull request merged**
